version: '3.3'

services:

  bank_account:
    container_name: bank
    build: ./
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000