version: '3.3'

services:

  bank_account:
    container_name: bank
    build: ./
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  mongodb:
    container_name: bankaccount
    build: ./mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./mongodb/backup:/backup
    ports:
      - 27017:27017
    restart: always
      
  