CREATE DATABASE IF NOT EXISTS bankaccount;
USE bankaccount;

CREATE TABLE IF NOT EXISTS customer  (
    id VARCHAR(200) PRIMARY KEY NOT NULL,
    lastname VARCHAR(200),
    firstname VARCHAR(200)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS account (
    id VARCHAR(200) PRIMARY KEY NOT NULL ,
    balance INT(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    account_owner VARCHAR(200) NOT NULL,
    CONSTRAINT fk_customer FOREIGN KEY (account_owner) REFERENCES customer(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS operation (
    id VARCHAR(200) PRIMARY KEY NOT NULL,
    balance INT(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    account_concerned VARCHAR(200) NOT NULL,
    CONSTRAINT fk_account FOREIGN KEY (account_concerned) REFERENCES account(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;